# Generated by Django 2.0.13 on 2020-02-22 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50, verbose_name='创建人')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('name', models.CharField(max_length=50, verbose_name='字段名')),
                ('field_key', models.CharField(max_length=50, verbose_name='字段标识')),
                ('ticket_id', models.IntegerField(verbose_name='工单id')),
                ('field_type_id', models.IntegerField(help_text='见service.constant_service中定义', verbose_name='字段类型')),
                ('char_value', models.CharField(blank=True, default='', max_length=1000, verbose_name='字符串值')),
                ('int_value', models.IntegerField(blank=True, default=0, verbose_name='整形值')),
                ('float_value', models.FloatField(blank=True, default=0.0, verbose_name='浮点值')),
                ('bool_value', models.BooleanField(default=False, verbose_name='布尔值')),
                ('date_value', models.DateField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='日期值')),
                ('datetime_value', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='日期时间值')),
                ('time_value', models.TimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0, 1), verbose_name='时间值')),
                ('radio_value', models.CharField(blank=True, default='', max_length=50, verbose_name='radio值')),
                ('checkbox_value', models.CharField(blank=True, default='', help_text='逗号隔开多个选项', max_length=50, verbose_name='checkbox值')),
                ('select_value', models.CharField(blank=True, default='', max_length=50, verbose_name='下拉列表值')),
                ('multi_select_value', models.CharField(blank=True, default='', help_text='逗号隔开多个选项', max_length=50, verbose_name='多选下拉列表值')),
                ('text_value', models.TextField(blank=True, default='', verbose_name='文本值')),
                ('username_value', models.CharField(blank=True, default='', max_length=50, verbose_name='用户名')),
                ('multi_username_value', models.CharField(blank=True, default='', max_length=1000, verbose_name='多选用户名')),
            ],
            options={
                'verbose_name': '工单自定义字段',
                'verbose_name_plural': '工单自定义字段',
            },
        ),
        migrations.CreateModel(
            name='TicketFlowLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50, verbose_name='创建人')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('ticket_id', models.IntegerField(verbose_name='工单id')),
                ('transition_id', models.IntegerField(help_text='与worklow.Transition关联， 为0时表示认为干预的操作', verbose_name='流转id')),
                ('suggestion', models.CharField(blank=True, default='', max_length=1000, verbose_name='处理意见')),
                ('participant_type_id', models.IntegerField(help_text='见service.constant_service中定义', verbose_name='处理人类型')),
                ('participant', models.CharField(blank=True, default='', max_length=50, verbose_name='处理人')),
                ('state_id', models.IntegerField(blank=True, default=0, verbose_name='当前状态id')),
                ('intervene_type_id', models.IntegerField(default=0, help_text='0.非人为干预的流转，1.转交操作 2.加签操作 3.加签处理完成', verbose_name='干预类型')),
                ('ticket_data', models.CharField(blank=True, default='', help_text='可以用于记录当前表单数据，json格式', max_length=10000, verbose_name='工单数据')),
            ],
            options={
                'verbose_name': '工单流转日志',
                'verbose_name_plural': '工单流转日志',
            },
        ),
        migrations.CreateModel(
            name='TicketRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50, verbose_name='创建人')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('title', models.CharField(blank=True, default='', help_text='工单的标题', max_length=500, verbose_name='标题')),
                ('workflow_id', models.IntegerField(help_text='与workflow.Workflow流程关联', verbose_name='关联的流程id')),
                ('sn', models.CharField(help_text='工单的流水号', max_length=25, verbose_name='流水号')),
                ('state_id', models.IntegerField(help_text='与workflow.State关联', verbose_name='当前状态')),
                ('parent_ticket_id', models.IntegerField(default=0, help_text='与ticket.TicketRecord关联', verbose_name='父工单id')),
                ('parent_ticket_state_id', models.IntegerField(default=0, help_text='与workflow.State关联,子工单是关联到父工单的某个状态下的', verbose_name='对应父工单状态id')),
                ('participant_type_id', models.IntegerField(default=0, help_text='0.无处理人,1.个人,2.多人,3.部门,4.角色', verbose_name='当前处理人类型')),
                ('participant', models.CharField(blank=True, default='', help_text='可以为空(无处理人的情况，如结束状态)、username\\多个username(以,隔开)\\部门id\\角色id\\脚本文件名等', max_length=100, verbose_name='当前处理人')),
                ('relation', models.CharField(blank=True, default='', help_text='工单流转过程中将保存所有相关的人(包括创建人、曾经的待处理人)，用于查询', max_length=1000, verbose_name='工单关联人')),
                ('in_add_node', models.BooleanField(default=False, help_text='是否处于加签状态下', verbose_name='加签状态中')),
                ('add_node_man', models.CharField(blank=True, default='', help_text='加签操作的人，工单当前处理人处理完成后会回到该处理人，当处于加签状态下才有效', max_length=50, verbose_name='加签人')),
                ('script_run_last_result', models.BooleanField(default=True, verbose_name='脚本最后一次执行结果')),
                ('is_end', models.BooleanField(default=False, help_text='工单是否已处于结束状态', verbose_name='已结束')),
                ('is_rejected', models.BooleanField(default=False, help_text='工单是否处于被拒绝状态', verbose_name='被拒绝')),
                ('multi_all_person', models.CharField(blank=True, default='{}', help_text='需要当前状态处理人全部处理时实际的处理结果，json格式', max_length=1000, verbose_name='全部处理的结果')),
            ],
            options={
                'verbose_name': '工单记录',
                'verbose_name_plural': '工单记录',
            },
        ),
    ]
